// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proxyarr.Dedupe.Db;

#nullable disable

namespace Proxyarr.Dedupe.Db.Migrations
{
    [DbContext(typeof(ProxyarrDbContext))]
    partial class ProxyarrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Proxyarr.Dedupe.Db.Claim", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("JobId", "Instance");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("Proxyarr.Dedupe.Db.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NzoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupKey", "ContentKey")
                        .IsUnique();

                    b.HasIndex("GroupKey", "NzoId")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Proxyarr.Dedupe.Db.Claim", b =>
                {
                    b.HasOne("Proxyarr.Dedupe.Db.Job", "Job")
                        .WithMany("Claims")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Proxyarr.Dedupe.Db.Job", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
